version: '3.7'
services:
  hackadb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: hackuser
      MONGO_INITDB_ROOT_PASSWORD: hackpass
      MONGO_INITDB_DATABASE: hackaton
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - hackanet

networks:
  hackanet:

volumes:
  mongodb_data_container:
